import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className="flex">
          {/* sidebar */}


          {/* client provider - notification */}

          <div className="flex-1 bg-[#343541]">{children}</div>
          {/* sidebar */}
          {/* sidebar */}
        </div>
      </body>
    </html>
  )
}
